#!/usr/bin/env python

import os
import shutil
from diffusers import StableDiffusionLatentUpscalePipeline
from diffusers.pipelines.stable_diffusion.safety_checker import (
    StableDiffusionSafetyChecker,
)


MODEL_ID = "stabilityai/sd-x2-latent-upscaler"
MODEL_CACHE = "diffusers-cache"
SAFETY_MODEL_ID = "CompVis/stable-diffusion-safety-checker"

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

saftey_checker = StableDiffusionSafetyChecker.from_pretrained(
    SAFETY_MODEL_ID,
    cache_dir=MODEL_CACHE,
)

pipe = StableDiffusionLatentUpscalePipeline.from_pretrained(
    MODEL_ID,
    cache_dir=MODEL_CACHE,
)
